### ISSUE TITLE
Show warning if select_multiple value has spaces

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#106]
@theywa, it may be interesting and useful to follow the procedure of getting [the feature you added in Enketo Core](https://github.com/enketo/enketo-core/issues/510), activated in Enketo Express. In this case, I expect it to be straightforward, but it will be good to test and this way you can also see how translation strings get added to Enketo Express and how the modal dialog works (automagically).

* update enketo-core package.json (the commit that added the feature or the latest enketo-core commit) 
* `npm install` and then run with `grunt develop`
* update changelog of enketo-express (just copy entry from enketo-core)
* do final test with actual forms. There are two methods I use:
1. Upload a form to e.g. KoBoCAT and then manually make an API call to your local enketo-express installation with that form, using the [POST /survey](https://apidocs.enketo.org/v2#/post-survey) api call. After that you can open your form in the browser using the returned URL. 
2. Upload a form anywhere on a webserver and use the `http://localhost:8005/preview?form=http://theurl/to/form.xml`
* You should be seeing the nice modal dialogs instead of window.alert.
* While running `grunt develop` the new translation key should have been automatically detected and added to `/locales/src/en/translation.json`. You have to copy the English string that you used in fake-translator.js in enketo-core). Once the commit is pushed to master, the translators will be automatically alerted that there is a new string to be translated (in Transifex).

**Comment by MartijnR** [comment]
I have already updated enketo-core in 930ed1c9fabc3ea7e10c679ea1b0f90e4dbf07d7 (because of another feature that was added after yours), and your translation string has been added. I haven't tested it though, so it would still be good to do that.

**Comment by theywa** [comment]
@MartijnR, I found an issue when testing. The modal dialog only showed the last alert message like this 
![test-result1](https://user-images.githubusercontent.com/13865076/62514985-8d10de00-b853-11e9-97d7-e9093df34407.png)
when it supposedly showed 3 alerts. My guess this happens because of the modal dialog worked differently than the alert window. Alert window will pause the load process until the user closes it and the modal dialog will be fired after the process is done so the message got override with the new one. I think maybe we can save all the message on an array then call the dialog.alert at the end of the loop with all the array of message joined with break line, like 
```js
if ( multiple && ( value.indexOf( ' ' ) > -1 ) ) {
      alerts[alerts.length] = t( 'alert.valuehasspaces.multiple', { value: value } );
} 
...
if ( alerts.length > 0 ) {
      dialog.alert( alerts.join("<br>") );
}
```
and the modal dialog will look like 
![test-maybe-solution](https://user-images.githubusercontent.com/13865076/62515933-483a7680-b856-11e9-9169-dce05c59e7d3.png)
or we can just join the value in 1 message like 
![test-maybe-solution2](https://user-images.githubusercontent.com/13865076/62516323-5b017b00-b857-11e9-81cd-59f5cd713fc0.png)

**Comment by MartijnR** [comment]
Yes, let's do this!

 We're assuming the enketo-core-consuming app has a dialog that supports some basic HTML rendering, but if that's not the case we can deal with that when somebody reports a problem.

**Comment by theywa** [comment]
@MartijnR - I create [PR](https://github.com/enketo/enketo-core/pull/645) in enketo-core

**Comment by theywa** [comment]
Testing works as expected by manually update enketo-core on package.json to github:enketo/enketo-core#c91cc7b1
![Screenshot from 2019-08-08 15-39-25](https://user-images.githubusercontent.com/13865076/62684271-e8c59d80-b9f2-11e9-97fa-67cb09fba3ff.png)
Should create PR to update enketo-core in package.json?

**Comment by MartijnR** [comment]
Great. Thanks for checking. I have to commit something else to enketo-express now, so I'll update to enketo-core 5.5.2  (otherwise, yes, feel free to just create PRs like that - would be great).
