### ISSUE TITLE
swipe page configuration has no effect

### ISSUE THREAD

**Issue by kryptt** [enketo/enketo-express#124]
Hi, the swipe page configuration added in 1.58 currently has no code associated to it ("did a quick grep in the current repo for "swipePage") and setting it to false still allows for swiping to change pages.

**Comment by MartijnR** [comment]
Hi,

Thanks for reporting!

The code is in the form engine 'enketo-core': https://github.com/enketo/enketo-core/blob/91efa707e0ff1b25631a718d45d74fe28d72ca42/src/js/page.js.

Did you rebuild Enketo Express (`grunt`) after changing the config?

If so, we should investigate a possible issue with passing configuration items.

**Comment by kryptt** [comment]
From what I gather; the docker image rebuilds Enketo on deploy; and when I load a page in the browser. its value is false, but the code snippet you shared is not present for us. 

![Screenshot from 2019-11-27 11-39-03](https://user-images.githubusercontent.com/107965/69716603-a2fc2480-110a-11ea-969d-b0ac9715b9be.png)

This is the docker image we are using: 
image: kobotoolbox/enketo-express-extra-widgets:1.79.0

**Comment by MartijnR** [comment]
Hi @kryptt,

Yes, it looks like that build is not correct. I don't know what the cause is (and am not familiar with docker). There was an issue with one of the build dependencies (rollup-plugin-alias) in the last few months but I don't understand why the `if()` statement is missing. That seems a different issue.

I did verify that the setting works in the latest Enketo Express. You  can inspect the JS here to confirm (when) your build is correct: https://enke.to/::pages.

Cheers,
