### ISSUE TITLE
Keep client configuration as a separate file?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#163]
Instead of bundling it with all the javascripts. Helps with (docker) deployment #161.

**Comment by mlazowik** [comment]
This is a solution that makes the most sense to me: https://stackoverflow.com/a/53624829/5769763

Saving config to `window` somewhere in index.html before any other js resources is IMO safer than loading from a separate js file, because the risk of accidentally overcaching is pretty much gone. If you cache index too much you have a problem either way.

(Of course I'm not talking about offline support at all here, this is about regular cache/cdn caching).

**Comment by MartijnR** [comment]
That sounds pretty good to me. Maybe like this?:

* [ ] keep enketo-core as-is where enketo/config resolves to a file
* [ ] in enketo-express, add the content of require('config-model').client to webform.pug
* [ ] in enketo-express, resolve enketo/config to a new module that simply reads window.env (with an empty `{}` as fallback)

**Comment by mlazowik** [comment]
Yup, this way the way the config is passed to the container stays the same, right?

**Comment by MartijnR** [comment]
Are you asking whether the config is editable by the user this way? I think we can and should avoid that in client-config.js.

**Comment by mlazowik** [comment]
Nope, I meant that this would not be a breaking change (no need to modify how the config is provided).

**Comment by MartijnR** [comment]
Thanks, well this sounds like a fun project. PR very welcome (and a simplified docker config too of course, but that should be separate).

**Comment by MartijnR** [comment]
@jnm, is perhaps any KoBo dev interested in implementing this very cool project?

**Comment by MartijnR** [comment]
Your silence is crystal clear @jnm :smirk: Or maybe you forgot but were actually very excited to do this. In that case, sorry you've missed the opportunity and it is too late now!

How about reviewing/testing the PR and do your exciting [docker update](#162) based on this?  :wink:

**Comment by mlazowik** [comment]
@MartijnR FYI the links in your last comment are broken :)

**Comment by jnm** [comment]
Hi @MartijnR, this is a great improvement and much appreciated. KoBo can see about taking advantage of it to simplifying the Docker configuration as time permits. This can't be high-priority for us because we already have a workaround to reduce startup time, i.e. not running `grunt` if neither the configuration nor the application code has changed. I'm also uninterested in reducing the image size as mentioned in #162; my concerns are simplicity and fast startup time. Perhaps a reduction in the image size could be an ancillary benefit.
