### ISSUE TITLE
Browser default language is prioritized over the form's default language

### ISSUE THREAD

**Issue by FrankApiyo** [enketo/enketo-express#222]
**Describe the bug**
Browser default language is prioritized over the form's default language

**To Reproduce**
1. Ensure your browser's default language is English
2. Open the following form in enketo-express 
3. Note that it's rendered in English (instead of French)
[multilang.xlsx](https://github.com/enketo/enketo-express/files/5702743/multilang.xlsx)
The above forms' default language is French. but if your browser's default language is English, it's rendered in english

**Expected behavior**
Form's default should be prioritized over the Browser's default

**Comment by MartijnR** [comment]
Hi Frank, 

These are the different scenarios: https://docs.google.com/spreadsheets/d/1CigMLAQewcXi-OJJHi_JQQ-fJXOam99livM0oYrtbkk/edit#gid=0

Your form is not using the correct syntax. Please follow https://xlsform.org/en/#multiple-language-support.

Please re-open if you find that there is still an issue.

**Comment by MartijnR** [comment]
Actually, it looks like the behavior is deliberate and makes sense to me (first scenario in table). The form's default language is considered less important than browser language if both are available in the form. The forms default language only does something if the browser language is not available in the form and is otherwise ignored.

The common use case would be to collect data from respondents in multiple languages.

It's seems far less common to want to override that, right? (but you can with `?lang=`).

**Comment by FrankApiyo** [comment]
Thanks, it seemed deliberate to me too. I'm just not sure why/how this form
has deviated from the correct syntax
