### ISSUE TITLE
Load an instanceID that was using a previous form version

### ISSUE THREAD

**Issue by kryptt** [enketo/enketo-express#253]
## Revisiting old submissions is not immutable. 
If I load the response (instanceID) of a kobotoolbox form that has multiple versions I will see the old response within the template (structure) of the new form. So; if I remove an question that had been previously filled, or if I rename its ID then the answer orginally given will not be shown. 

We would like to be able to evolve forms and still maintain consistency of the previously inputted data.

## Alternative pathway
What we are currently thinking of doing is simply create a new question (form id) for the content whenever we notice we will be making breaking changes. But since we often *re-visit* submission instances, it would be better for us to have a guarantee that what is loaded also matches what was initially input.

## Proposed solution
It would be nice if a parameter can be set / sent to override which version of the form template data will be read from the open rosa server (kobotoolbox).  This way we can choose to load a given instance with the same form revision it was originally submitted, or allow the submission to be edited with the new question structure.

Does this make sense?

**Comment by MartijnR** [comment]
Thank you @kryptt. I can see this would be useful.

@jnm, @lognaturel have you come across this requirement as well?

Some thoughts on implementation:

* /formList would have to publish all versions of a form (not sure if the case currently in Central, KoBo, Ona)
* for the /instance/edit functionality enketo would search formList for the form version in the instance
* tricky thing would be form caching. Not sure if Enketo should cache all versions of a form (whenever requested and it doesn't exist) or just ignore the cache altogether for non-latest versions of a form when editing an instance. This would make editing records of old form versions slow but probably simplify the implementation
* currently Enketo first loads the latest version of a form and then loads the instance. This would have to change by perhaps including the form version in the URL.

**Comment by lognaturel** [comment]
It would be helpful to get actual scenarios in which you're removing fields from production forms, @kryptt. E.g. is it because you realize a field isn't actionable? Because you want to merge two questions in to one? Negate the wording? Here are some strategies I've used: https://github.com/getodk/docs/issues/1344

As described in that docs issue, I typically recommend using relevance or changing types to `calculate`s in cases where fields need to be suppressed from the user experience but maintained in the schema. I don't think we would expose the feature proposed here unless possibly if it were more of a one-time thing where a link to a specific schema XML could be passed in. The downsides of publishing all versions to `/formList` are pretty significant.

**Comment by lognaturel** [comment]
We're considering this an issue for form servers to handle pending further information.
