### ISSUE TITLE
Add setting to disable last-saved cache from being populated

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#292]
For groups that have sensitive (patient) data that should not be cached.

I vaguely recall we may have a similar setting with the same concern for a different feature.

Just wanted to post this, but I will do some more research.

ping @pbowen-oc

**Comment by lognaturel** [comment]
It should only be populated if the form definition includes `last-saved` so it's inherently feature-flagged. It's also only saved for online and offline -- an edit to a submission belonging to a form that has a `last-saved` reference will not result in that submission being saved browser-side. It would certainly be good to get extra review on that and on the test cases but that is the intent. As far as I know, there's no case in which it would make sense to have `last-saved` in an online or offline form but not actually want the caching behavior. If the caching behavior is undesirable, `last-saved` should be removed from the form definition.

As discussed in https://github.com/enketo/enketo-express/issues/286 and https://github.com/enketo/enketo-express/pull/288, there are currently regressions that break media in online mode and expand caching. That's not intentional and @eyelidlessness is working on a patch.

**Comment by MartijnR** [comment]
>  it's inherently feature-flagged

Ah, that's perfect! @pbowen-oc, so preventing those forms from being uploaded prevents the cache from being created.
