### ISSUE TITLE
Improve error message when external data not found

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo-express#363]
If you preview a form (e.g., one with pulldata) where the data itself is not attached, this is the error message we get.

<img width="593" alt="Screen Shot 2021-11-10 at 14 41 27" src="https://user-images.githubusercontent.com/32369/141207699-c379ce56-e725-4047-b3f8-4163c58843de.png">

It'd be better if the error message was more helpful. For example, "filename.ext is missing."

These errors happen on http://xlsform.getodk.org/ when forms that use attachments are submitted (we don't support attachments, but don't communicate that to folks) or people are trying to preview a draft in Central (we only warn if they try to publish it).

**Comment by yanokwa** [comment]
I just ran into this issue again. There's plenty of room for improvement on error messages across the codebase, but @eyelidlessness how hard/easy is it to fix this specific one?

**Comment by eyelidlessness** [comment]
@yanokwa I've tried to reproduce this error with the described scenario, but thus far I haven't been able. Can you provide a form and reproduction steps?

However, I was able to produce an error with the same message in a different scenario. I don't know if it's the same one, but it did surface a bug I can fix! I'll file that next.

**Comment by eyelidlessness** [comment]
Okay I think I've figured out why I couldn't reproduce this. I was trying to "preview" in my local Central environment, but it's a **different preview** than what's on http://xlsform.getodk.org/. The latter uses the URL pattern `/preview?form={xmlURL}`, whereas the former uses `/preview/{enketoId}`. This triggers [different behavior](https://github.com/enketo/enketo-express/blob/98ce11e53f0e77fac48a5c8acd00a5deb5c69fbc/public/js/src/module/connection.js#L502-L505) when external instance requests fail.

This then dovetails with the bug I found. Because these errors are being swallowed, that `return` statement is populating the survey's `externalData` elements with `undefined`. Then when we [check for](https://github.com/enketo/enketo-express/blob/98ce11e53f0e77fac48a5c8acd00a5deb5c69fbc/public/js/src/module/last-saved.js#L19-L22) a last-saved external instance, the above error is thrown instead of "Failed to fetch". Unless you object, I'm going to treat this as the same bug and file it that way.

The good news is this is an easy fix. I'm assuming we still want to show an error here for Central's preview with `enketoId`? If so, I can easily improve the error message along with the fix.

**Comment by yanokwa** [comment]
I did a bit of research and this is was [done on purpose](https://github.com/OpenClinica/enketo-express-oc/issues/376). In my opinion, the desired behavior for both URL patterns should be, as @MartijnR [wrote](https://github.com/OpenClinica/enketo-express-oc/issues/376#issuecomment-705150592)...
>show external file errors together with any form load errors, but still show the form (and disable submissions).

That is, the form should load and work as best as it can, but we should know there are problems. Curious what @lognaturel thinks.

P.S. The xlsform.getodk.org code is here: https://github.com/getodk/xlsform-online/blob/ad21e7bf767255242a1767dcc19aef346c20b7fd/xlsform_app/templates/upload.html#L60.

**Comment by lognaturel** [comment]
> the form should load and work as best as it can, but we should know there are problems (e.g., "Can't find file.csv"). 

Agreed. 

I have no idea whether that’s realistic but seems like an opportunity to see whether the same behavior in different contexts can be harmonized.

**Comment by lognaturel** [comment]
Just tried this on https://getodk.org/xlsform/ and it's Very Nice®.
