### ISSUE TITLE
Configure and/or limit number of node processes

### ISSUE THREAD

**Issue by bufke** [enketo/enketo-express#372]
**Is your feature request related to a problem? Please describe.**

Imagine the following two use cases representing a simplistic deployment and a more complex one.

- You have one server with 32 cores. When deploying enketo express for a very minor use case, you end up with 32 processes when you might need only 1 or 2. This is an inefficient use of resources.
- You deploy enketo express to a Kubernetes cluster with a 1 cpu node. You inspect memory usage and set requests and limits. Later, the pod gets scheduled on a 64 cpu node, easily available today on AWS EC2 for example and very reasonable for a larger Kubernetes cluster. It is not likely in this scenario a user would desire 64 processes and the request/limits would be way off. There is no reason the admin would expect different memory requirements based on the underlying hardware node the pod runs on.

**Describe the solution you'd like**

IMO the cleanest solution would be environment variables/config values to set an explicit processes number as well as a configurable max process allowed. Something like `NUM_PROCESSES` which defaults to "auto" and `MAX_PROCESSES` which defaults to null for backwards compatibility.

**Describe alternatives you've considered**

The app.js file is not very large and a user could write their own and customize the start pm2 or node command. However this is tedious and would result in having to duplicate code that might be changed at a later date.

Another alternative is to change the default behavior. That's a little scary as it could be a breaking change. However it would be really nice for a developer running enketo and has many cpu cores.

**Additional context**

See existing process logic [here](https://github.com/enketo/enketo-express/blob/master/app.js#L10)

**Comment by bufke** [comment]
I propose the following changes:

- Set the max limit default to 16 processes. This will provide immediate relief to users with many CPUs and avoid the worse case scenarios where these processes get OOM killed or lock up the machine. It should be considered a potentially breaking change, but seems unlikely to affect many users. It would need to be clearly documented in release notes nonetheless.
- Add a environment variable to override the max instances. app.js doesn't currently process the JSON config file. I would propose making this an environment variable only. That's a little odd but is a simple solution.

Smaller instances that don't have this many threads, can simply ignore it.

I'm happy to open a PR if this solution is acceptable.

**Comment by eyelidlessness** [comment]
I think this is an excellent idea. Saturating all of the available cores is generally not optimal past ~4 cores. Another scenario which would almost certainly benefit is on systems with [simultaneous multithreading (SMT, also known as HyperThreading)](https://en.wikipedia.org/wiki/Simultaneous_multithreading), where sometimes utilizing only half the cores may perform better. I'd certainly welcome a PR!

As far as implementation:

- I'd like to make sure it's configurable in `config.json` (even if it may default to an environment variable for flexibility, as some configs in `config-model.json` appear to be). I'm cautious about introducing an env-only configuration, as it could make debugging and investigating issues more challenging. `app.js` currently brings in the config only in workers, via `config/express.js` > `app/models/config-model.js`. That indirection is probably not appropriate for the main process, but I think importing `config-model.js` is probably okay.

- I think 16 is a fine default maximum. To the extent it's a breaking change, it's probably a desirable one and it's easily overridden if someone really does want that many processes. Separate from this smaller bit of work, but for discussion:
  - I think it's worth considering setting the default to `numCPUs - 2` where `numCPUs` is greater than 4 and less than 18.
  - We should also consider how easy it would be to use [worker threads](https://nodejs.org/api/worker_threads.html) rather than forked processes, at least as an option. It would almost certainly perform better in all scenarios, and definitely the ones discussed here.

**Comment by bufke** [comment]
I can try using config in app.js. Worker threads seem good if that works for us. I'm always surprised Node doesn't seem to have a standard way of deploying like uwsgi in Python. I can research. In the k8s/heroku/anything that scales horizontally use case, a thread would make more sense as there would be greater memory savings. Without that efficiency, there's no point at all launching multiple.

16 was my answer to be as safe of a change as possible. Personally I don't think we should tie hardware to desired configuration at all. Better to let the user choose.

**Comment by bufke** [comment]
I'm not sure how to get worker threads working with express. It doesn't seem like a common thing to do though most answers I find infuriatingly assume the reader surely cares about io bound and not cpu bound processes. I also couldn't say if the ee is thread safe or not.

I'm going to focus on only the configuration for limiting processes.
