### ISSUE TITLE
NetworkError when attempting to fetch resource with Enketo 3.0.X

### ISSUE THREAD

**Issue by qlands** [enketo/enketo-express#388]
**Describe the bug**
I have form that works fine with ODK Collect but when I try to open it with Enketo Express it produces the error: "NetworkError when attempting to fetch resource". There is no information in the logs.

**To Reproduce**
You can download the form here: http://www.qlands.com/other_files/maize_form.zip it has several CSVs that the form uses with select_one_from_file and pulldata

**Expected behavior**
The form should work or show a better description of the error

**Browser and OS**
 - OS: Linux. Enketo 3.0.5-p running from Docker
 - Browser: Firefox

**Comment by lognaturel** [comment]
Can't reproduce on 4.0.1. Looks like a form design issue. You're mixing two ways of attaching CSV data: `select_one_from_file` and implicit attachment with `pulldata`. In your usage of `pulldata` you've specified `filename.csv` so you'd have to make sure to upload `filename.csv.csv`. There's also a `duration` calculate that will need to be fixed to use references.

**Comment by lognaturel** [comment]
This was still kicking around my brain and I remembered you said ODK Collect works fine. The `pulldata` implementation in Collect is entirely outside the ODK XForms spec and has a fair amount of flexibility built into it. I haven't verified this but my guess is that it's permissive when it comes to filename extensions where Enketo is not. What probably makes the most sense is to use `filename` as the first parameter rather than `filename.csv` to get consistent behavior.
