### ISSUE TITLE
CSP and security headers

### ISSUE THREAD

**Issue by bufke** [enketo/enketo-express#399]
**Is your feature request related to a problem? Please describe.**

[Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) and other security related headers are a part of best deployment practices. There are a number of ways to set these headers in both the application and network (CDN/Load Balancer) layers.

**Describe the solution you'd like**

I'd like to propose for discussion adding these headers when relevant with configurable but sane defaults. This can assist end users who may not be using a CDN, serverless platform, or load balancer that supports setting headers. A benefit of setting these in application code is that it "just works" for users who might be inexperienced in what these headers are or how to set them.

I find [helmet](https://github.com/helmetjs/helmet) to be a useful tool for setting these in an express application.

**Describe alternatives you've considered**

Adjusting headers could be considered out of project scope. Other options would be

- Add nginx in front of the express server and append headers there
- Extend the project's app.js when deploying

**Additional context**

If there was appetite for including this in scope, the next steps would be to determine what sane defaults are and what needs to be configurable. 

For examples of what others do - [Django](https://docs.djangoproject.com/en/4.0/ref/middleware/#module-django.middleware.security) is a large project that includes options to enable these headers in the application layer. The Helmet project has 8k stars at this time.

**Comment by eyelidlessness** [comment]
Hi @bufke, thank you for filing this issue.

I certainly think it would be good to support this. I’m not particularly familiar with CSP (though a bit more today!). My inclination is to copy someone else’s defaults, perhaps modified if any of them stand out as unreasonable for Enketo users.

The nginx alternative sounds compelling at first glance, but that may unnecessarily constrain deployment options for some users.

As far as configuration, it seems reasonable to me to expose all of them as options, unless there’s a compelling reason not to. I might even go further and suggest that configuration of headers could be more general.

I’m open to being convinced otherwise on this, but I’m hesitant to use the helmet library:

- as a general caution about adding production dependencies
- particularly as they may affect security
- especially as a third party middleware, which tends to make it hard to reason about the request/response cycle
- supporting it directly should almost certainly be trivial

**Comment by bufke** [comment]
Sounds good. Helmet might offer good defaults even if we don't use it directly. I should be able to work on this when I have time. It should be pretty trivial to add the headers. I believe it would make sense to offer a HSTS option but it needs to be configurable and disabled by default.

**Comment by eyelidlessness** [comment]
Excellent, we'd appreciate a PR if you would like to contribute this. Agree HSTS should be supported/off by default.

**Comment by bufke** [comment]
I drafted support just for HSTS, please let me know if this is the correct way to add configuration options and middleware. It looks like I'll need to update 10-configure.md as well.

I'll work on CSP next. I'm wondering if it's safest to make that disabled by default as well.
