### ISSUE TITLE
Time selector does not work with finnish locale

### ISSUE THREAD

**Issue by MikaVilpo** [enketo/enketo-express#453]
**Describe the bug**

**To Reproduce**
Create form with datetime field
Set browser language to finnish
Unable to save form as AM/PM selector contains only ,

**Expected behavior**
24 hour timeformat is used

**Screenshots**
![image](https://user-images.githubusercontent.com/44055222/184500192-08e403ba-b616-4a93-8864-a45c1109a9a2.png)

**Browser and OS (please complete the following information):**
- Windows 11, Edge

**Additional context**
Formatting as 24 hour clock works fine if locale in browser is set Swedish.

**Comment by eyelidlessness** [comment]
Thanks for filing this. I've looked into the bug, and it appears the problem is that the current solution depends on a regular expression expecting `:` separators rather than `.`. Adding that case to the regex would be a naive quick fix, but would leave likely other localization issues unaddressed.

Instead, I'm inclined to revise the time parsing and formatting logic to use the standard [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) APIs. It'll be a larger change, but should address localization of the input more holistically.
