### ISSUE TITLE
Unused dependency: jstransformer-markdown-it

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-express#473]
**Describe the bug**
There appears to be an unused dependency: 

https://github.com/enketo/enketo-express/blob/6b3ba99375acf3357eda7cc4b85cd11e64e64a7d/package.json#L64

**Comment by alxndrsn** [comment]
Could this be an implicit dependency of `pug`?  (`pug` seems to be an implicit dependency of `enketo-transformer`.)

**Comment by lognaturel** [comment]
Isn't it for JSDoc generation?

**Comment by alxndrsn** [comment]
> Isn't it for JSDoc generation?

If so, could it be moved to `devDependencies`?

**Comment by eyelidlessness** [comment]
This is actually used [here](https://github.com/enketo/enketo-express/blob/906a32bbc2be4200ad033d0a84d301e35dc625cf/app/views/index.pug#L90) to render the changelog on the express index page. This is done dynamically at runtime, so requires a production dependency.

That said, I don't know that this provides any more value than a GitHub link.

**Comment by lognaturel** [comment]
Two cases where it might provide more/different value:
- Forks can keep their personal changelog updated and not have to change the link.
- Entirely offline servers still get a changelog

I'm not sure these are super compelling but they do seem worth mentioning. Because of the fork situation I think if we don't render the changelog inline we probably can't/shouldn't link to anything.

It's not clear to me what the audience of the change information in Express really is. Whoever is administering the server should be able to get the changelog as needed from where its source is managed. Savvy users might be able to hypothesize that an issue they experience is related to a change in the changelog but it's not clear what they then do with that information. Presumably they have to report the issue either here or to whoever runs the server.

**Comment by eyelidlessness** [comment]
Okay, we'll err on no change for now. Closing since this one is actually needed for prod for now.
