### ISSUE TITLE
Integer and decimal widgets disappear after switching language

### ISSUE THREAD

**Issue by jnm** [enketo/enketo-express#507]
**Describe the bug**

For a form with two languages, integer and decimal questions appear initially, but after switching to the second language, they disappear. They do not return after switching back to the first language.

I've seen #495, #496, etc., but this problem happens even when `config.json` either
* contains no `widgets` override, or
* contains an array of `widgets` that explicitly includes `integer` and `decimal`.

The problem does _not_ happen on https://enketo.getodk.org/, but that instance reports to be running `version: 5.0.0-4-g67bf890`. I couldn't find that commit in this repository. If there's a hotfix somewhere, I'd love to use it :smiley:

**To Reproduce**

Use this minimal XLSForm: [numbers-missing-after-language-switch.xlsx](https://github.com/enketo/enketo-express/files/10256271/numbers-missing-after-language-switch.xlsx)
type | name | label::OK | label::NG
-- | -- | -- | --
integer | int_q | OK int | NG int
decimal | dec_q | OK dec | NG dec
text | txt_q | OK txt | NG txt

1. Check out tag `5.0.0` from this repository
1. Create a minimal `config.json`, e.g.
    ```json
    {
        "port": "8999",
        "encryption key": "insecure-enketo-dev",
        "linked form and data server": {
            "api key": "insecure-enketo-dev",
            "server url": ""
        },
        "redis": {
            "cache": {
                "host": "10.6.6.1",
                "password": "insecure-redis-dev",
                "port": "60667"
            },
            "main": {
                "host": "10.6.6.1",
                "password": "insecure-redis-dev",
                "port": "60667"
            }
        }
    }
    ```
1. `npm run start` etc.
1. Use [XLSForm Online](https://getodk.org/xlsform/) to generate the XForm from numbers-missing-after-language-switch.xlsx (above)
    1. Click "Preview in browser" and see that it works properly
    1. Grab the path and query string, e.g. `preview?form=https%3A//xlsform.getodk.org/downloads/xbeexfwc/numbers-missing-after-language-switch.xml`
1. Use that path and query string with local Enketo 5.0.0, e.g. `http://localhost:8999/preview?form=https%3A//xlsform.getodk.org/downloads/xbeexfwc/numbers-missing-after-language-switch.xml`
1. See that things look good initially: 
![image](https://user-images.githubusercontent.com/2085013/208358349-2f0ac5f9-cdf2-4692-8047-ac1f29bc1f27.png)
1. Switch to "NG" language
1. See that integer and decimal questions disappear while the text question remains: 
![image](https://user-images.githubusercontent.com/2085013/208358385-ede36a0d-2d35-47d1-9a2a-96e45e0286f2.png)
1. Switch back to "OK" language and see that the questions are still gone.

**Browser and OS (please complete the following information):**

-   OS: Linux
-   Browser: Firefox and Chrome

**Comment by jnm** [comment]
Aha. If I provide an array of `widgets` that _excludes_ `integer` and `decimal`, going back to the [old](https://github.com/enketo/enketo-core/issues/792) widgets that treat values like `--` as valid, then language switching works.

I think that explains the behavior on XLSForm Online:
![image](https://user-images.githubusercontent.com/2085013/208363127-f5ba4856-48c3-433a-9f42-ab44a17c7f71.png)

**Comment by lognaturel** [comment]
Thanks for reporting this, @jnm, and for your patience as we deal with these frustrating regressions.

How did you spot this one? We had talked previously about you sharing some checks that you might do, that would still be helpful if you have some automated or not. Functionality interacts in ways we don't always expect and tests only cover so many combinations.

> that instance reports to be running version: 5.0.0-4-g67bf890

The `g` prefix stands for `git` and acts like a kind of namespace. That server updates on each commit to master and is running https://github.com/enketo/enketo-express/commit/67bf89034a082db8d861003654c51b1b1a801b19

As you noted later, the issue is present in that version too.

There's a likely fix at https://github.com/enketo/enketo-core/pull/937. We want to do a bit more validation on it and the fix for https://github.com/enketo/enketo-core/issues/934 tomorrow and hope to have Core and Express releases available by mid-day PST.

**Comment by lognaturel** [comment]
One of the changes made to reduce the risk of data loss due to invalid numeric input is to set the lang attribute on numeric controls. This is broadly recommended (eg https://www.ctrl.blog/entry/html5-input-number-localization.html). However, form translations are done by hiding every element with lang attributes that don’t also have an `active` attribute. We’re trying to fix this current issue in a way that makes sense and allows broader use of the lang attribute which is good for accessibility.

**Comment by jnm** [comment]
> The `g` prefix stands for `git` and acts like a kind of namespace. That server updates on each commit to master and is running [67bf890](https://github.com/enketo/enketo-express/commit/67bf89034a082db8d861003654c51b1b1a801b19)

Hah, shame on me. I even looked at the manual for `git describe` and missed the part about the `g` prefix. Thanks for the lesson!

> How did you spot this one? We had talked previously about you sharing some checks that you might do, that would still be helpful if you have some automated or not. Functionality interacts in ways we don't always expect and tests only cover so many combinations.

Unfortunately, I did not spot it :flushed: The Kobo users didn't waste any time finding it, though :dart: I try to run a public beta for most releases, but I did not have one for this release. In the past, volunteers have spotted some important issues, but overall participation has been limited to a few power users.

> Thanks for reporting this, @jnm, and for your patience as we deal with these frustrating regressions.

I very much appreciate your hard work as maintainers. Sorry to make your year-end more hectic. If there's anything I can do to help, please let me know.

**Comment by lognaturel** [comment]
> overall participation has been limited to a few power users

Yes, that's what we're finding too. In general we are not very satisfied with how we do (or don't) get feedback about Enketo as part of the release process. Ideas for improvement are welcome.

When you find regressions, getting a feel for how severe you find it, whether it's in production, and how it has been found would be helpful. We try to prioritize regressions but it can be pretty disruptive so if you consider it minor or you're not deploying yet anyway that would be very helpful to know. It can also take us some time to feel like we have a safe and thoughtful fix when we run into unexpected interactions like we did here.
