### ISSUE TITLE
Webforms no longer loading on Samsung Internet browser app

### ISSUE THREAD

**Issue by PorterTR** [enketo/enketo-express#83]
After the most recent update on 2019-02-15, webforms used for offline data collection no longer load in the Samsung Internet browser. We've switched over to Chrome (which wasn't working for the same reason two weeks back) moving forward, but I'm concerned about retrieving both saved drafts and completed locally stored forms under the Samsung browser. Any guidance you could provide on the issue would be appreciated.

Samsung Galaxy Tab A (2016), Android 5.1.1

**Comment by MartijnR** [comment]
> but I'm concerned about retrieving both saved drafts and completed locally stored forms under the Samsung browser

It sounds like downgrading Enketo Express is the only solution.

We won't fix "Samsung Internet" specific bugs ourselves, but if there is a supported browser that has issues, let us know. Nothing has changed in offline technologies for a very long time, but there could be some exception that occurs elsewhere in the code (due to modernization).

**Comment by PorterTR** [comment]
Thanks for the prompt response. I was able to update the Samsung browser to a more recent version (8.2.01.2--highest allowable on this OS version) and can now load the survey again. We'll continue using Chrome from here on out, though. Glad to be able to continue on with such a great tool.
