### ISSUE TITLE
Unable to edit read_only questions based on prev questions responses

### ISSUE THREAD

**Issue by smusula** [enketo/enketo-express#90]
If you have select multiple questions (Q1) with options A and B, one of the responses is selected by default e.g option A and it's also read-only. One is able to successfully make submissions. However, when you try to edit this submission,  and for the second option by selecting option B. 
**Steps to recreate:**

1. Go to [this Enketo form](https://enketo.unhcr.org/x/#y5YFj26z), at Q1 select only A and submit the form.
2. Then, go to the edit link of the submitted form, and select B. You will notice that the default response option is not marked – thus unable to select B and re-submit.

**Environment**
- Web browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Platform: https://kobo.unhcr.org
- XLSForm used: https://docs.google.com/spreadsheets/d/1oRi__WJrlXaBOJeIl3fMXfpCRrBu94tOBt5IF89H-YU/edit?usp=sharing

**Comment by MartijnR** [comment]
Thank you!

* [ ] see if reproducible by setting A as default for Q1, in form definition

**Comment by MartijnR** [comment]
I am not able to reproduce this. It's possible Enketo has been updated since.

@smusula, does the record you are editing look like this in the KoBo interface (with both A and A1 reponses)?
<img width="1035" alt="Screen Shot 2019-03-28 at 5 30 01 PM" src="https://user-images.githubusercontent.com/627350/55199313-4f9e9480-517f-11e9-9e68-3ddc487f61ff.png">

**Comment by smusula** [comment]
@MartijnR yes, that's what I have:
![editing](https://user-images.githubusercontent.com/4832172/55222117-612d7e00-520b-11e9-8982-7648a5a2d295.PNG)

As seen in the screenshot below, when B is selected during editing the default responses are not selected:
![editing_QB](https://user-images.githubusercontent.com/4832172/55222396-152f0900-520c-11e9-9f6b-e96743cbc74d.PNG)

**Comment by MartijnR** [comment]
Ah thank you. Sorry, I hadn't read your OP correctly. This is by design. When the record is submitted all non-relevant values are emptied. Defaults are gone from that point onwards. I think this is correct behavior.

In the future you might be able to circumvent that using a new feature. Not sure how it will be called in XLSForm but's called '<setvalue>` in XForms.
