### ISSUE TITLE
Adding custom widgets doesn't do anything

### ISSUE THREAD

**Issue by LeonardFollner** [enketo/enketo-express#94]
I am looking into adding a custom widget to enketo express. Therefore I followed [the documentation](https://github.com/enketo/enketo-express/blob/master/doc/custom-widgets.md). 

I copied the code for my widget from the [`textarea`](https://github.com/enketo/enketo-core/blob/master/src/widget/textarea/textarea.js). It is located under `<project-root>/custom-widget/myWidget.js`. 

My `config.json` looks like this:
```json
{
    "widgets": [
        "note", 
        "select-desktop", 
        [...]
        "../../../node_modules/enketo-image-customization-widget/image-customization", 
        "../../../node_modules/enketo-literacy-test-widget/literacywidget", 
        "../../../custom-widgets/myWidget"
    ], 
[...]
}
```

The widget is found, since I do get an error in the compiler, if I cause one on purpose. Still I don't see it in the UI.

Are there any further steps required to register a custom widget to appear in the UI?

**Comment by MartijnR** [comment]
Hi Leonard, 

If it's not proprietary, could you post/link to your widget code perhaps? Does the selector match anything in your form?

Note, I find it much easier to develop a custom widget using only enketo-core (and once it works, move it to enketo-express as you've done). 

> Are there any further steps required to register a custom widget to appear in the UI?
No, there aren't.

**Comment by LeonardFollner** [comment]
Hey Martijn,  
thank you for the fast response.  
The code of my widget is just exactly the code from the [textarea-widget](https://github.com/enketo/enketo-core/blob/master/src/widget/textarea/textarea.js).  

I was not aware that further markup was required, but it totally makes sense.  
It is my original goal to add a new question-type to [kobotoolbox](https://github.com/kobotoolbox). Our potential users will often be illiterate and the questions in KoBoToolbox are mostly of textual nature. In our current solution we are using what could be described as a picture-based _select one_.  
I could not find documentation on how to add new question types. The only [guide on customization](https://github.com/kobotoolbox/enketo-express/blob/master/doc/custom-widgets.md) is regarding custom widgets.  
How would I go about adding something like this into KoBoToolbox? Can you describe the necessary steps to achieve this to me?

**Comment by MartijnR** [comment]
Do you have `<textarea>` elements in your form? How do you determine that the widget is not loading? Did you add some logging code to the _init function?

A new question type would likely be implemented as a widget, so that's great. You probably saw this link: https://github.com/enketo/enketo-core/blob/master/doc/widgets.md. I'm assuming your question type requirement is not yet covered by the picture based select-one questions on https://enke.to/::widgets.

We don't have better guidance than that, though you may want to have a look at [this](https://enketo.org/develop/#transformation) too, as the HTML transformation result is what the widgets operate on (not on the XForm directly). 

I'd recommend developing it in enketo-core for a more joyful development experience, and then install it in enketo-express according to the guidance you found. This avoids having to fork anything and all the headaches in keeping forks up to date. You could overwrite one of the select one picture based questions or add a custom appearance in your XLSForm, that your widget operates on.

Hope this helps.
